
server:
  port: 8080
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      rotate: true
      rename-on-rotate: true
      pattern: common
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:LocalSearchDb
    driver-class-name: org.h2.Driver
    username: sa
    password:


app:
  search-count: 10
  kakao:
    server: https://dapi.kakao.com
    rest-api-key: 1a3e3a7cdd1377bb20830ff9acc2e617
  naver:
    server: https://openapi.naver.com
    client-id: O8Ksq9eCLH2uvyd0AuhQ
    client-secret: eB1EE9va9t